name: Integration

# act does not see the job if no event exists
on:
  push:
    branches:
      - test-local-123
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.ref != 'refs/head/master/' || github.run_number }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  test-integration:
    runs-on: ubuntu-20.04
    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v3
        with:
          path: .

#      - name: 🧰 Setup Node
#        uses: actions/setup-node@v3
#        with:
#          cache: ${{ !env.ACT && 'npm' || '' }}
#          node-version: '16'
#
#      - name: 📦 Install Dependencies
#        run: npm i --ignore-scripts

      - name: 🧪 Test Draw
        uses: crisboarna/cfn-diagram-action@master
        with:
          path_input: test/data/input/**/*.yaml
          path_output: /dia
          viewport_width: 1920
          viewport_height: 1080
          diagram_type: d

      - name: 🧪 Verify API Draw
        run: diff dia/API.drawio test/data/output/draw/API.drawio

      - name: 🧪 Verify VPC_ELB Draw
        run: diff dia/vpc/VPC_ELB.drawio test/data/output/draw/VPC_ELB.drawio

      - name: 🧪 Verify VPC_Redshift Draw
        run: diff dia/vpc/VPC_Redshift.drawio test/data/output/draw/VPC_Redshift.drawio

      - name: 🧪 Test Html
        uses: crisboarna/cfn-diagram-action@master
        with:
          path_input: test/data/input/**/*.yaml
          path_output: /dia
          viewport_width: 1920
          viewport_height: 1080
          diagram_type: h

      # Vis.js generates nodes in random positions, simple base64 or img diff tools will have too low similarity to be of value
      - name: 🧪 Verify API Html
        run: test -e dia/API.png

      - name: 🧪 Verify VPC_ELB Html
        run: test -e dia/vpc/VPC_ELB.png

      - name: 🧪 Verify VPC_Redshift Html
        run: test -e dia/vpc/VPC_Redshift.png
